# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               RajR's Blog
tagline:             "My attempt at blogging. You like it?"
description:         A blog by software engineer and food enthusiast.
url:                 https://rajr0.github.io
baseurl:             https://rajr0.github.io/
paginate:            5
#google_analytics_id: UA-56228338-1

# About/contact
author:
  name:              Rajesh R
  url:               https://rajr0.github.io/
  email:             rramanku@hotmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-feed
